### ISSUE TITLE
Switch The Platform from radio buttons to checkboxes

### ISSUE THREAD

**Issue by jonearley** [mlibrary/litgoals#15]
I may need to do some styling to get these similar to how radio buttons are displayed.

**Comment by billdueber** [comment]
Implemented and fixed.

**Comment by jonearley** [comment]
@billdueber Can you tag these issues in your related commits? `#15`

**Comment by jonearley** [comment]
It will help me find the changes and work on the most up to date version.

**Comment by jonearley** [comment]
I don't see these changes at http://dueberb.www.lib.umich.edu/litgoals/new_goal so reopening.

**Comment by jonearley** [comment]
The platform field was removed. No longer needed.
