### ISSUE TITLE
Switch dropdowns to radio fieldsets

### ISSUE THREAD

**Issue by jonearley** [mlibrary/litgoals#2]

**Comment by jonearley** [comment]
@billdueber please switch the field "Goal Scope" and "The Platform" to radio buttons instead of a select/dropdown:

- [ ] Goal Scope: https://github.com/mlibrary/litgoals/blob/master/views/new_goal.erb#L19
- [ ] The Platform: https://github.com/mlibrary/litgoals/blob/master/views/new_goal.erb#L65

The same as how "Status" is displayed as radio options.

**Comment by billdueber** [comment]
Take care of with #9

**Comment by jonearley** [comment]
@billdueber could you add `class="radio-label"` back into the radio labels? Looks like that was lost. For example: http://earleyj.www.lib.umich.edu/goals-visualization-ui/

**Comment by billdueber** [comment]
@jonearley Looking into this. Might have to do it "by hand" in a loop, but have a request in on the mialing list for the form generator. Either way, it'll happen.

**Comment by jonearley** [comment]
@billdueber thank you!

**Comment by billdueber** [comment]
This turns out to be a pain. Can you just change the style target to `div.radioset label.option` ?

**Comment by jonearley** [comment]
Sure thing! It's better practice to use the class, but not worth it if it's a pain. I'll style it without the class.

**Comment by billdueber** [comment]
No, I meant that instead of `label.radio-label { color: red}` you would have `div.radioset label.option { color: red} `

**Comment by jonearley** [comment]
Right, we're talking about the same thing. It's better practice to use a single class instead of a chained selectors, but for this case I'll do a `label.option`.
