### ISSUE TITLE
Add save as draft option when creating a goal

### ISSUE THREAD

**Issue by jonearley** [mlibrary/litgoals#4]

**Comment by jonearley** [comment]
For example: http://earleyj.www.lib.umich.edu/goals-visualization-ui/

**Comment by jonearley** [comment]
![save_as_draft](https://cloud.githubusercontent.com/assets/1678665/17981090/26a54490-6ad0-11e6-9440-3f545dafbfc4.png)

**Comment by billdueber** [comment]
I'll look into this. We'll also need a way to display draft status on the goals page.

**Comment by jonearley** [comment]
In my latest UI I have the draft status shown in the goal status. Preview:

<img width="654" alt="screen shot 2016-08-26 at 9 05 15 am" src="https://cloud.githubusercontent.com/assets/1678665/18006214/8f19086c-6b6c-11e6-9aa4-f06c19d2f39e.png">

I'll update those today. Now I'm thinking the "associated" information should be "goal scope"

**Comment by jonearley** [comment]
@billdueber OK all you should have to do now is pass in the goal status: https://github.com/mlibrary/litgoals/blob/master/views/goals.erb#L75

**Comment by jonearley** [comment]
@billdueber thanks this is great!

http://earleyj.www.lib.umich.edu/goals-visualization-ui/goals.html

To match the UI designs, could you remove "Goal Status: Published"? It should either display Draft or it's goal status value (Not started, On hold, In progress, Completed, Abandoned). Hope that that makes sense, let me know.

A side note: I'm thinking the "Save" button might make more sense to say "Publish", but I'll think on it and maybe test the UI again.
