### ISSUE TITLE
Improve site messages

### ISSUE THREAD

**Issue by billdueber** [mlibrary/litgoals#5]
I've got it ugly. Currently in layout; I'd like to keep it there if possible.

**Comment by jonearley** [comment]
Falafel has a class called "alert" for flash/alert/messages. We can use that.

https://github.com/mlibrary/litgoals/blob/master/goals-visualization-ui/stylesheets/partials/_alerts.scss

**Comment by jonearley** [comment]
Preview:

![screenshot-localhost 3000 2016-08-24 10-19-39](https://cloud.githubusercontent.com/assets/1678665/17934010/4c78ed58-69e4-11e6-82b8-69f20eba0066.png)

**Comment by jonearley** [comment]
@billdueber merged a solution. Closing this issue.
