### ISSUE TITLE
Produce appropriate styles for error/warning messages

### ISSUE THREAD

**Issue by billdueber** [mlibrary/litgoals#8]
Right now, when  goal is successfully edited/created, I try to display something like:

> Goal <title> edited

...but I have no way to style the title to differentiate it from the surrounding text.  Maybe define a span class or something? Or give guidance on how to create a better message.

**Comment by jonearley** [comment]
@billdueber this is a duplicate issue that has been resolved and merged in a PR. Please see: https://github.com/mlibrary/litgoals/issues/5
